from core.research.community.discovery import (
    CommunityDiscussionScorer,
    CommunityDiscoveryEngine,
    DiscoveredDiscussionCandidate,
    DiscussionDiscoveryParams,
    DiscussionDiscoveryResult,
    normalize_community_id,
    normalize_discussion_id,
    normalize_discussion_url,
)
from core.research.community.extractor import (
    DiscussionCodeBlock,
    DiscussionContentExtractor,
    DiscussionLink,
    DiscussionQuote,
    StructuredDiscussion,
    StructuredDiscussionPost,
)
from core.research.community.fake_provider import FakeDiscussionProvider
from core.research.community.link_handoff import (
    CandidateLink,
    LinkHandoffPipeline,
    LinkHandoffPolicy,
)
from core.research.community.providers import (
    GitHubDiscussionsProvider,
    HackerNewsDiscussionProvider,
    RateLimitedDiscussionProvider,
    RedditJsonProvider,
    StackExchangeDiscussionProvider,
)
from core.research.community.models import (
    AccessStatus,
    CommunityContext,
    CommunityPlatform,
    Discussion,
    DiscussionComment,
    DiscussionPost,
    DiscussionSourceMaterial,
    DiscussionStatus,
    EngagementMetrics,
    ThreadOrdering,
    ThreadStructure,
    compute_sha256,
    sanitize_author_identifier,
    utc_now,
)
from core.research.community.provider import (
    DiscussionCommentsParams,
    DiscussionFetchLimits,
    DiscussionProvider,
    DiscussionRetrievalParams,
    DiscussionSearchParams,
    DiscussionSearchResponse,
)
from core.research.community.retriever import (
    BatchThreadRetrievalParams,
    BatchThreadRetrievalResult,
    DiscussionRetrievalLimits,
    DiscussionThreadRetriever,
    RetrievedDiscussionThread,
    ThreadRetrievalRequest,
)
from core.research.community.selection import (
    DiscussionRelevanceScorer,
    DiscussionSelectionEngine,
    DiscussionSelectionParams,
    DiscussionSelectionResult,
    DiscussionTopicQuery,
    ScoredDiscussionPost,
    SelectedDiscussionContext,
)

__all__ = [
    "AccessStatus",
    "BatchThreadRetrievalParams",
    "BatchThreadRetrievalResult",
    "CommunityContext",
    "CommunityDiscussionScorer",
    "CommunityDiscoveryEngine",
    "CommunityPlatform",
    "DiscoveredDiscussionCandidate",
    "Discussion",
    "DiscussionCodeBlock",
    "DiscussionComment",
    "DiscussionCommentsParams",
    "DiscussionContentExtractor",
    "DiscussionDiscoveryParams",
    "DiscussionDiscoveryResult",
    "DiscussionFetchLimits",
    "DiscussionLink",
    "DiscussionPost",
    "DiscussionProvider",
    "DiscussionQuote",
    "DiscussionRelevanceScorer",
    "CandidateLink",
    "DiscussionRetrievalLimits",
    "DiscussionRetrievalParams",
    "DiscussionSearchParams",
    "DiscussionSearchResponse",
    "DiscussionSelectionEngine",
    "DiscussionSelectionParams",
    "DiscussionSelectionResult",
    "DiscussionSourceMaterial",
    "DiscussionStatus",
    "DiscussionThreadRetriever",
    "DiscussionTopicQuery",
    "EngagementMetrics",
    "FakeDiscussionProvider",
    "GitHubDiscussionsProvider",
    "HackerNewsDiscussionProvider",
    "LinkHandoffPipeline",
    "LinkHandoffPolicy",
    "RateLimitedDiscussionProvider",
    "RedditJsonProvider",
    "RetrievedDiscussionThread",
    "StackExchangeDiscussionProvider",
    "ScoredDiscussionPost",
    "SelectedDiscussionContext",
    "StructuredDiscussion",
    "StructuredDiscussionPost",
    "ThreadOrdering",
    "ThreadRetrievalRequest",
    "ThreadStructure",
    "compute_sha256",
    "normalize_community_id",
    "normalize_discussion_id",
    "normalize_discussion_url",
    "sanitize_author_identifier",
    "utc_now",
]




