"""
Structured Data Subsystem Package (Phase 1 / Part 7).

Exposes provider-neutral domain models, schema representations, and location
addressing utilities for machine-readable structured sources (REST APIs, GraphQL,
JSON, JSONL, XML, CSV).
"""
from core.research.structured.fake_provider import (
    URL_CORRUPT,
    URL_CSV_DATA,
    URL_EMPTY_204,
    URL_ITEMS_ARRAY,
    URL_PAGINATED,
    URL_STATUS,
    URL_USER_NESTED,
    URL_XML_FEED,
    FakeStructuredDataProvider,
)
from core.research.structured.models import (
    FieldSegment,
    HttpMethod,
    IndexSegment,
    PaginationConfig,
    PaginationMetadata,
    PaginationType,
    PathSegment,
    SchemaField,
    SchemaStructureType,
    SourceLocation,
    StructuredContentType,
    StructuredDataLimits,
    StructuredDataRequest,
    StructuredDataResponse,
    StructuredDataSource,
    StructuredDataType,
    StructuredRecord,
    StructuredSchema,
    StructuredSourceType,
    WildcardSegment,
    canonical_json_dumps,
    compute_structured_hash,
)
from core.research.structured.builder import StructuredDataRequestBuilder
from core.research.structured.paginator import (
    BoundedRetrievalLimits,
    PaginatedRetrievalResult,
    RetrievalStatus,
    StructuredDataPaginator,
    extract_pagination_metadata,
    parse_link_header,
)
from core.research.structured.parser import (
    ParsedStructuredData,
    StructuredResponseParser,
)
from core.research.structured.auth import (
    CredentialRedactor,
    CredentialReference,
    CredentialResolver,
    CredentialType,
    ResolvedCredentials,
)
from core.research.structured.policy import StructuredDataSecurityPolicy
from core.research.structured.provider import StructuredDataProvider
from core.research.structured.query import (
    FilterOperator,
    LocalStructuredQueryEngine,
    OrderDirection,
    QueryFilter,
    QueryOrder,
    QueryResult,
    RemoteQueryContract,
    RemoteQueryMapper,
    StructuredQuery,
    evaluate_filter,
    extract_field_value,
    project_record,
    validate_field_path,
)
from core.research.structured.rate_limiter import (
    RateLimitConfig,
    RateLimitedStructuredDataProvider,
    parse_retry_after,
)

__all__ = [
    "CredentialType",
    "CredentialReference",
    "ResolvedCredentials",
    "CredentialResolver",
    "CredentialRedactor",
    "RateLimitConfig",
    "RateLimitedStructuredDataProvider",
    "parse_retry_after",
    "FilterOperator",
    "OrderDirection",
    "QueryFilter",
    "QueryOrder",
    "StructuredQuery",
    "QueryResult",
    "LocalStructuredQueryEngine",
    "RemoteQueryContract",
    "RemoteQueryMapper",
    "evaluate_filter",
    "extract_field_value",
    "project_record",
    "validate_field_path",
    "StructuredDataPaginator",
    "RetrievalStatus",
    "BoundedRetrievalLimits",
    "PaginatedRetrievalResult",
    "extract_pagination_metadata",
    "parse_link_header",
    "StructuredResponseParser",
    "ParsedStructuredData",
    "StructuredDataSecurityPolicy",
    "StructuredDataRequestBuilder",
    "StructuredDataProvider",
    "FakeStructuredDataProvider",
    "URL_CORRUPT",
    "URL_CSV_DATA",
    "URL_EMPTY_204",
    "URL_ITEMS_ARRAY",
    "URL_PAGINATED",
    "URL_STATUS",
    "URL_USER_NESTED",
    "URL_XML_FEED",

    "FieldSegment",
    "HttpMethod",
    "IndexSegment",
    "PaginationConfig",
    "PaginationMetadata",
    "PaginationType",
    "PathSegment",
    "SchemaField",
    "SchemaStructureType",
    "SourceLocation",
    "StructuredContentType",
    "StructuredDataLimits",
    "StructuredDataRequest",
    "StructuredDataResponse",
    "StructuredDataSource",
    "StructuredDataType",
    "StructuredRecord",
    "StructuredSchema",
    "StructuredSourceType",
    "WildcardSegment",
    "canonical_json_dumps",
    "compute_structured_hash",
]
