from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional
import uuid

from core.routing.types import RouteDestination, RoutingConfidenceTier


def utc_now() -> str:
    """Generate ISO 8601 UTC timestamp."""
    return datetime.now(timezone.utc).isoformat()


@dataclass
class RoutingContext:
    """
    Context package provided to the router to inform routing decisions.
    Contains conversation state, active project details, registered workers, and known entities.
    """
    conversation_context: list[dict[str, Any]] = field(default_factory=list)
    project_id: Optional[str] = None
    active_project_context: Optional[dict[str, Any]] = None
    available_workers: list[str] = field(
        default_factory=lambda: [
            "worker.researcher",
            "worker.programmer",
            "worker.tester",
        ]
    )
    task_metadata: dict[str, Any] = field(default_factory=dict)
    known_entities: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "conversation_context": list(self.conversation_context),
            "project_id": self.project_id,
            "active_project_context": self.active_project_context,
            "available_workers": list(self.available_workers),
            "task_metadata": dict(self.task_metadata),
            "known_entities": list(self.known_entities),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RoutingContext:
        return cls(
            conversation_context=list(data.get("conversation_context", [])),
            project_id=data.get("project_id"),
            active_project_context=data.get("active_project_context"),
            available_workers=list(
                data.get("available_workers", ["worker.researcher", "worker.programmer", "worker.tester"])
            ),
            task_metadata=dict(data.get("task_metadata", {})),
            known_entities=list(data.get("known_entities", [])),
        )


@dataclass
class RoutingProposal:
    """
    Untrusted analytical proposal generated by the LLM routing classifier.
    Must undergo deterministic validation before becoming an authoritative RoutingDecision.
    """
    proposal_id: str = field(default_factory=lambda: f"route-prop-{uuid.uuid4().hex[:8]}")
    route: str = ""
    confidence: float = 0.5
    reason: str = ""
    requires_external_information: bool = False
    requires_research_evidence: bool = False
    requires_project_context: bool = False
    requires_tool_execution: bool = False
    target_worker: Optional[str] = None
    suggested_stages: list[dict[str, Any]] = field(default_factory=list)
    ambiguities: list[dict[str, Any]] = field(default_factory=list)
    clarification_required: bool = False
    clarification_questions: list[str] = field(default_factory=list)
    model_used: Optional[str] = None
    provider_used: Optional[str] = None
    raw_response: Optional[str] = None
    created_at: str = field(default_factory=utc_now)

    def to_dict(self) -> dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "route": self.route,
            "confidence": self.confidence,
            "reason": self.reason,
            "requires_external_information": self.requires_external_information,
            "requires_research_evidence": self.requires_research_evidence,
            "requires_project_context": self.requires_project_context,
            "requires_tool_execution": self.requires_tool_execution,
            "target_worker": self.target_worker,
            "suggested_stages": list(self.suggested_stages),
            "ambiguities": list(self.ambiguities),
            "clarification_required": self.clarification_required,
            "clarification_questions": list(self.clarification_questions),
            "model_used": self.model_used,
            "provider_used": self.provider_used,
            "raw_response": self.raw_response,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RoutingProposal:
        return cls(
            proposal_id=str(data.get("proposal_id", f"route-prop-{uuid.uuid4().hex[:8]}")),
            route=str(data.get("route", "")),
            confidence=float(data.get("confidence", 0.5)),
            reason=str(data.get("reason", "")),
            requires_external_information=bool(data.get("requires_external_information", False)),
            requires_research_evidence=bool(data.get("requires_research_evidence", False)),
            requires_project_context=bool(data.get("requires_project_context", False)),
            requires_tool_execution=bool(data.get("requires_tool_execution", False)),
            target_worker=data.get("target_worker"),
            suggested_stages=list(data.get("suggested_stages", [])),
            ambiguities=list(data.get("ambiguities", [])),
            clarification_required=bool(data.get("clarification_required", False)),
            clarification_questions=[str(q) for q in data.get("clarification_questions", [])],
            model_used=data.get("model_used"),
            provider_used=data.get("provider_used"),
            raw_response=data.get("raw_response"),
            created_at=str(data.get("created_at", utc_now())),
        )


@dataclass
class RoutingDecision:
    """
    Authoritative routing decision produced by RequestRouter after deterministic validation.
    Instructs the runtime whether to bypass Researcher or route to a specific destination.
    """
    decision_id: str
    route: RouteDestination
    confidence: float
    confidence_tier: RoutingConfidenceTier
    reason: str
    requires_external_information: bool = False
    requires_research_evidence: bool = False
    requires_project_context: bool = False
    requires_tool_execution: bool = False
    target_worker: Optional[str] = None
    suggested_stages: list[dict[str, Any]] = field(default_factory=list)
    ambiguities: list[dict[str, Any]] = field(default_factory=list)
    clarification_required: bool = False
    clarification_questions: list[str] = field(default_factory=list)
    routing_trace: list[str] = field(default_factory=list)
    source_request_id: str = ""
    created_at: str = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    def is_research_required(self) -> bool:
        """Return True only if the authoritative route requires entering the Researcher pipeline."""
        return self.route == RouteDestination.RESEARCH

    def can_bypass_researcher(self) -> bool:
        """Return True if this decision completely bypasses the Researcher subsystem."""
        return self.route != RouteDestination.RESEARCH

    def to_dict(self) -> dict[str, Any]:
        return {
            "decision_id": self.decision_id,
            "route": self.route.value if isinstance(self.route, RouteDestination) else str(self.route),
            "confidence": self.confidence,
            "confidence_tier": self.confidence_tier.value if isinstance(self.confidence_tier, RoutingConfidenceTier) else str(self.confidence_tier),
            "reason": self.reason,
            "requires_external_information": self.requires_external_information,
            "requires_research_evidence": self.requires_research_evidence,
            "requires_project_context": self.requires_project_context,
            "requires_tool_execution": self.requires_tool_execution,
            "target_worker": self.target_worker,
            "suggested_stages": list(self.suggested_stages),
            "ambiguities": list(self.ambiguities),
            "clarification_required": self.clarification_required,
            "clarification_questions": list(self.clarification_questions),
            "routing_trace": list(self.routing_trace),
            "source_request_id": self.source_request_id,
            "created_at": self.created_at,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RoutingDecision:
        r_raw = data.get("route", RouteDestination.FAILED.value)
        try:
            route = RouteDestination(r_raw)
        except (ValueError, TypeError):
            route = RouteDestination.FAILED

        tier_raw = data.get("confidence_tier", RoutingConfidenceTier.MEDIUM.value)
        try:
            tier = RoutingConfidenceTier(tier_raw)
        except (ValueError, TypeError):
            tier = RoutingConfidenceTier.MEDIUM

        return cls(
            decision_id=str(data.get("decision_id", f"route-dec-{uuid.uuid4().hex[:8]}")),
            route=route,
            confidence=float(data.get("confidence", 0.5)),
            confidence_tier=tier,
            reason=str(data.get("reason", "")),
            requires_external_information=bool(data.get("requires_external_information", False)),
            requires_research_evidence=bool(data.get("requires_research_evidence", False)),
            requires_project_context=bool(data.get("requires_project_context", False)),
            requires_tool_execution=bool(data.get("requires_tool_execution", False)),
            target_worker=data.get("target_worker"),
            suggested_stages=list(data.get("suggested_stages", [])),
            ambiguities=list(data.get("ambiguities", [])),
            clarification_required=bool(data.get("clarification_required", False)),
            clarification_questions=list(data.get("clarification_questions", [])),
            routing_trace=list(data.get("routing_trace", [])),
            source_request_id=str(data.get("source_request_id", "")),
            created_at=str(data.get("created_at", utc_now())),
            metadata=dict(data.get("metadata", {})),
        )
