"""
Project Context Models, Providers, and Discovery Package (Phase 1 / Part 8).
"""
from core.research.errors import (
    ProjectAccessError,
    ProjectCancelledError,
    ProjectContextError,
    ProjectFileNotFoundError,
    ProjectMalformedFileError,
    ProjectNotFoundError,
    ProjectProviderError,
    ProjectResourceLimitError,
    ProjectSecurityError,
    ProjectTimeoutError,
    ProjectValidationError,
)
from core.research.project.context_extractor import (
    ProjectConfigurationExtractor,
    ProjectContextExtractor,
    ProjectDependencyExtractor,
    ProjectDocumentationExtractor,
)
from core.research.project.discovery import (
    DEFAULT_GENERATED_PATTERNS,
    KNOWN_CONFIG_DIRS,
    KNOWN_DOCS_DIRS,
    KNOWN_MANIFEST_ECOSYSTEM_MAP,
    KNOWN_SOURCE_ROOT_NAMES,
    KNOWN_TEST_DIRS,
    DiscoveredProjectStructure,
    ProjectDiscoveryOptions,
    ProjectStructureDiscoverer,
    classify_manifest_ecosystem,
    detect_source_roots,
    is_documentation_file_path,
    is_generated_file_path,
    is_manifest_path,
    is_test_file_path,
)
from core.research.project.extractor import (
    ExtractedProjectFile,
    ProjectContractClassifier,
    ProjectExtractionOptions,
    ProjectSourceExtractor,
)
from core.research.project.fake_provider import FakeProjectWorkspaceProvider
from core.research.project.local_provider import LocalProjectWorkspaceProvider
from core.research.project.models import (
    ProjectConfigType,
    ProjectConfigurationMetadata,
    ProjectContext,
    ProjectContract,
    ProjectContractType,
    ProjectDependencyMetadata,
    ProjectDependencyType,
    ProjectDirectory,
    ProjectDocSection,
    ProjectDocumentationMetadata,
    ProjectFile,
    ProjectIdentity,
    ProjectSourceMaterial,
    ProjectStructure,
    ProjectSymbol,
    ProjectType,
    ProjectVCSContext,
    ProjectVCSState,
    mask_sensitive_config,
    normalize_project_path,
)
from core.research.project.provider import (
    IGNORED_PROJECT_NAMES,
    ProjectFetchLimits,
    ProjectFileParams,
    ProjectTreeParams,
    ProjectWorkspaceProvider,
    is_sensitive_project_path,
)
from core.research.project.selector import (
    CATEGORY_PRIORITY,
    CandidateProjectFile,
    ProjectContextSelector,
    ProjectRelevanceScorer,
    ProjectSelectionOptions,
    ProjectSelectionQuery,
    SelectedProjectContext,
    classify_project_file_category,
)
from core.research.project.vcs import (
    ProjectVCSInspector,
    ProjectVCSOptions,
)

__all__ = [
    # Errors
    "ProjectContextError",
    "ProjectValidationError",
    "ProjectSecurityError",
    "ProjectNotFoundError",
    "ProjectProviderError",
    "ProjectFileNotFoundError",
    "ProjectAccessError",
    "ProjectMalformedFileError",
    "ProjectResourceLimitError",
    "ProjectTimeoutError",
    "ProjectCancelledError",
    # Models & Enums
    "ProjectType",
    "ProjectConfigType",
    "ProjectContractType",
    "ProjectDependencyType",
    "ProjectVCSState",
    "ProjectIdentity",
    "ProjectDirectory",
    "ProjectStructure",
    "ProjectFile",
    "ProjectSourceMaterial",
    "ProjectSymbol",
    "ProjectContract",
    "ProjectDocSection",
    "ProjectDocumentationMetadata",
    "ProjectConfigurationMetadata",
    "ProjectDependencyMetadata",
    "ProjectVCSContext",
    "ProjectContext",
    "normalize_project_path",
    "mask_sensitive_config",
    # Providers & Limits
    "IGNORED_PROJECT_NAMES",
    "is_sensitive_project_path",
    "ProjectFetchLimits",
    "ProjectTreeParams",
    "ProjectFileParams",
    "ProjectWorkspaceProvider",
    "FakeProjectWorkspaceProvider",
    "LocalProjectWorkspaceProvider",
    # Discovery Engine (Part 8.3)
    "ProjectDiscoveryOptions",
    "DiscoveredProjectStructure",
    "ProjectStructureDiscoverer",
    "KNOWN_MANIFEST_ECOSYSTEM_MAP",
    "KNOWN_TEST_DIRS",
    "KNOWN_DOCS_DIRS",
    "KNOWN_CONFIG_DIRS",
    "KNOWN_SOURCE_ROOT_NAMES",
    "DEFAULT_GENERATED_PATTERNS",
    "is_manifest_path",
    "classify_manifest_ecosystem",
    "is_test_file_path",
    "is_documentation_file_path",
    "is_generated_file_path",
    "detect_source_roots",
    # Selection Engine (Part 8.4)
    "CandidateProjectFile",
    "ProjectSelectionQuery",
    "ProjectSelectionOptions",
    "ProjectRelevanceScorer",
    "SelectedProjectContext",
    "ProjectContextSelector",
    "classify_project_file_category",
    "CATEGORY_PRIORITY",
    # Source & Contract Extraction (Part 8.5)
    "ProjectExtractionOptions",
    "ExtractedProjectFile",
    "ProjectContractClassifier",
    "ProjectSourceExtractor",
    # Documentation, Config & Dependencies Extraction (Part 8.6)
    "ProjectDocumentationExtractor",
    "ProjectConfigurationExtractor",
    "ProjectDependencyExtractor",
    "ProjectContextExtractor",
    # VCS & Workspace State Inspection (Part 8.7)
    "ProjectVCSOptions",
    "ProjectVCSInspector",
]

