from abc import ABC, abstractmethod
from typing import Optional

from core.enums import MemoryType, TaskStatus, WorkerStatus
from core.events.model import Event
from core.events.types import EventType
from core.memory.model import MemoryDocument
from core.models import Artifact, Dependency, Project, Task, WorkerManifest


class Store(ABC):
    """Abstract persistence layer interface for AutonomOS runtime."""

    # Project Operations
    @abstractmethod
    def save_project(self, project: Project) -> None:
        """Persist or update a project."""
        pass

    @abstractmethod
    def get_project(self, project_id: str) -> Optional[Project]:
        """Retrieve a project by ID."""
        pass

    @abstractmethod
    def list_projects(self) -> list[Project]:
        """List all projects."""
        pass

    @abstractmethod
    def delete_project(self, project_id: str) -> bool:
        """Delete a project by ID."""
        pass

    # Worker Operations
    @abstractmethod
    def save_worker(self, worker: WorkerManifest) -> None:
        """Persist or update a worker manifest."""
        pass

    @abstractmethod
    def get_worker(self, worker_id: str) -> Optional[WorkerManifest]:
        """Retrieve a worker by ID."""
        pass

    @abstractmethod
    def list_workers(self) -> list[WorkerManifest]:
        """List all registered workers."""
        pass

    @abstractmethod
    def delete_worker(self, worker_id: str) -> bool:
        """Remove a worker by ID."""
        pass

    @abstractmethod
    def update_worker_status(self, worker_id: str, status: WorkerStatus, active_task_id: Optional[str] = None) -> None:
        """Atomically update a worker's lifecycle status and active task."""
        pass

    # Task Operations
    @abstractmethod
    def save_task(self, task: Task) -> None:
        """Persist or update a task."""
        pass

    @abstractmethod
    def get_task(self, task_id: str) -> Optional[Task]:
        """Retrieve a task by ID."""
        pass

    @abstractmethod
    def list_tasks(self, project_id: Optional[str] = None, status: Optional[TaskStatus] = None) -> list[Task]:
        """List tasks with optional project and status filters."""
        pass

    @abstractmethod
    def get_tasks_by_parent(self, parent_task_id: str) -> list[Task]:
        """Retrieve child subtasks of a parent task."""
        pass

    @abstractmethod
    def delete_task(self, task_id: str) -> bool:
        """Delete a task by ID."""
        pass

    # Dependency Operations
    @abstractmethod
    def add_dependency(self, dependency: Dependency) -> None:
        """Register a dependency between two tasks."""
        pass

    @abstractmethod
    def get_dependencies_for_task(self, task_id: str) -> list[Dependency]:
        """Get prerequisites that must complete before this task can run."""
        pass

    @abstractmethod
    def get_dependents_for_task(self, task_id: str) -> list[Dependency]:
        """Get tasks that depend on this prerequisite task."""
        pass

    @abstractmethod
    def remove_dependency(self, dependency_id: str) -> bool:
        """Remove a dependency edge."""
        pass

    # Artifact Operations
    @abstractmethod
    def save_artifact(self, artifact: Artifact) -> None:
        """Persist an artifact record."""
        pass

    @abstractmethod
    def get_artifact(self, artifact_id: str) -> Optional[Artifact]:
        """Retrieve an artifact by ID."""
        pass

    @abstractmethod
    def list_artifacts_for_task(self, task_id: str) -> list[Artifact]:
        """List all artifacts generated by a task."""
        pass

    @abstractmethod
    def list_artifacts_for_project(self, project_id: str) -> list[Artifact]:
        """List all artifacts belonging to a project."""
        pass

    # Event Store Operations (Stage 2)
    @abstractmethod
    def append_event(self, event: Event) -> Event:
        """Append an immutable event to the event log and assign a monotonic sequence number."""
        pass

    @abstractmethod
    def get_event(self, event_id: str) -> Optional[Event]:
        """Retrieve an event by ID."""
        pass

    @abstractmethod
    def list_events(
        self,
        project_id: Optional[str] = None,
        task_id: Optional[str] = None,
        worker_id: Optional[str] = None,
        correlation_id: Optional[str] = None,
        event_types: Optional[list[EventType]] = None,
        since_sequence: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> list[Event]:
        """Query events with flexible filtering ordered by sequence number."""
        pass

    @abstractmethod
    def get_events_by_correlation_id(self, correlation_id: str) -> list[Event]:
        """Retrieve all events belonging to a specific correlation/execution chain."""
        pass

    @abstractmethod
    def get_events_by_task(self, task_id: str) -> list[Event]:
        """Retrieve full chronological timeline of events for a specific task."""
        pass

    @abstractmethod
    def get_events_by_project(self, project_id: str) -> list[Event]:
        """Retrieve all events for a project."""
        pass

    @abstractmethod
    def get_causal_chain(self, event_id: str) -> list[Event]:
        """Reconstruct the causal lineage of events leading up to this event."""
        pass

    # Memory Store Operations (Stage 3)
    @abstractmethod
    def save_memory_document(self, doc: MemoryDocument) -> None:
        """Persist or update a memory document record."""
        pass

    @abstractmethod
    def get_memory_document(self, memory_id: str) -> Optional[MemoryDocument]:
        """Retrieve a memory document by ID."""
        pass

    @abstractmethod
    def get_memory_document_by_path(self, project_id: str, relative_path: str) -> Optional[MemoryDocument]:
        """Retrieve a memory document by relative path within a project."""
        pass

    @abstractmethod
    def list_memory_documents(
        self,
        project_id: Optional[str] = None,
        memory_type: Optional[MemoryType] = None,
        tag: Optional[str] = None,
        related_task_id: Optional[str] = None,
    ) -> list[MemoryDocument]:
        """List memory documents with optional filters."""
        pass

    @abstractmethod
    def delete_memory_document(self, memory_id: str) -> bool:
        """Delete a memory document record."""
        pass

    # Lifecycle
    @abstractmethod
    def close(self) -> None:
        """Close storage handles."""
        pass
