from abc import ABC, abstractmethod
from typing import Optional

from core.enums import TaskStatus, WorkerStatus
from core.models import Artifact, Dependency, Project, Task, WorkerManifest


class Store(ABC):
    """Abstract persistence layer interface for AutonomOS runtime."""

    # Project Operations
    @abstractmethod
    def save_project(self, project: Project) -> None:
        """Persist or update a project."""
        pass

    @abstractmethod
    def get_project(self, project_id: str) -> Optional[Project]:
        """Retrieve a project by ID."""
        pass

    @abstractmethod
    def list_projects(self) -> list[Project]:
        """List all projects."""
        pass

    @abstractmethod
    def delete_project(self, project_id: str) -> bool:
        """Delete a project by ID."""
        pass

    # Worker Operations
    @abstractmethod
    def save_worker(self, worker: WorkerManifest) -> None:
        """Persist or update a worker manifest."""
        pass

    @abstractmethod
    def get_worker(self, worker_id: str) -> Optional[WorkerManifest]:
        """Retrieve a worker by ID."""
        pass

    @abstractmethod
    def list_workers(self) -> list[WorkerManifest]:
        """List all registered workers."""
        pass

    @abstractmethod
    def delete_worker(self, worker_id: str) -> bool:
        """Remove a worker by ID."""
        pass

    @abstractmethod
    def update_worker_status(self, worker_id: str, status: WorkerStatus, active_task_id: Optional[str] = None) -> None:
        """Atomically update a worker's lifecycle status and active task."""
        pass

    # Task Operations
    @abstractmethod
    def save_task(self, task: Task) -> None:
        """Persist or update a task."""
        pass

    @abstractmethod
    def get_task(self, task_id: str) -> Optional[Task]:
        """Retrieve a task by ID."""
        pass

    @abstractmethod
    def list_tasks(self, project_id: Optional[str] = None, status: Optional[TaskStatus] = None) -> list[Task]:
        """List tasks with optional project and status filters."""
        pass

    @abstractmethod
    def get_tasks_by_parent(self, parent_task_id: str) -> list[Task]:
        """Retrieve child subtasks of a parent task."""
        pass

    @abstractmethod
    def delete_task(self, task_id: str) -> bool:
        """Delete a task by ID."""
        pass

    # Dependency Operations
    @abstractmethod
    def add_dependency(self, dependency: Dependency) -> None:
        """Register a dependency between two tasks."""
        pass

    @abstractmethod
    def get_dependencies_for_task(self, task_id: str) -> list[Dependency]:
        """Get prerequisites that must complete before this task can run."""
        pass

    @abstractmethod
    def get_dependents_for_task(self, task_id: str) -> list[Dependency]:
        """Get tasks that depend on this prerequisite task."""
        pass

    @abstractmethod
    def remove_dependency(self, dependency_id: str) -> bool:
        """Remove a dependency edge."""
        pass

    # Artifact Operations
    @abstractmethod
    def save_artifact(self, artifact: Artifact) -> None:
        """Persist an artifact record."""
        pass

    @abstractmethod
    def get_artifact(self, artifact_id: str) -> Optional[Artifact]:
        """Retrieve an artifact by ID."""
        pass

    @abstractmethod
    def list_artifacts_for_task(self, task_id: str) -> list[Artifact]:
        """List all artifacts generated by a task."""
        pass

    @abstractmethod
    def list_artifacts_for_project(self, project_id: str) -> list[Artifact]:
        """List all artifacts belonging to a project."""
        pass

    # Lifecycle
    @abstractmethod
    def close(self) -> None:
        """Close storage handles."""
        pass
