"""AutonomOS Application Layer — Boundary, DTOs, Services, and Stream."""
from __future__ import annotations

from app.application import AutonomOSApp
from app.dto import (
    ActivityItemDTO,
    AppError,
    AppException,
    ApprovalRequestDTO,
    ApprovalResponse,
    ArtifactDTO,
    Conversation,
    ConversationMessage,
    CycleResultDTO,
    DecisionRequestDTO,
    ErrorCode,
    EventDTO,
    EventStreamEnvelope,
    EvidenceDTO,
    HandoffDTO,
    ManagerStatusDTO,
    MessageType,
    ModelDTO,
    PlanDTO,
    ProjectCreateRequest,
    ProjectDTO,
    ProjectSummaryDTO,
    ProviderDTO,
    TaskCreateRequest,
    TaskDTO,
    TaskSummaryDTO,
    UserInputRequestDTO,
    WorkerDTO,
    WorkerSummaryDTO,
    WorkflowDTO,
    normalize_error,
)
from app.services import (
    ApprovalService,
    ArtifactService,
    ConversationService,
    EventService,
    PolicyService,
    ProjectService,
    ProviderService,
    TaskService,
    WorkerService,
    WorkflowService,
)
from app.stream import EventStreamConnection, EventStreamEnvelope, EventStreamManager

__all__ = [
    "AutonomOSApp",
    # DTOs
    "ProjectDTO",
    "ProjectSummaryDTO",
    "ProjectCreateRequest",
    "TaskDTO",
    "TaskSummaryDTO",
    "TaskCreateRequest",
    "WorkerDTO",
    "WorkerSummaryDTO",
    "WorkflowDTO",
    "HandoffDTO",
    "ApprovalRequestDTO",
    "UserInputRequestDTO",
    "DecisionRequestDTO",
    "ApprovalResponse",
    "ArtifactDTO",
    "EvidenceDTO",
    "ManagerStatusDTO",
    "PlanDTO",
    "CycleResultDTO",
    "ProviderDTO",
    "ModelDTO",
    "EventDTO",
    "ActivityItemDTO",
    "EventStreamEnvelope",
    "Conversation",
    "ConversationMessage",
    "MessageType",
    "AppError",
    "AppException",
    "ErrorCode",
    "normalize_error",
    # Services
    "ProjectService",
    "TaskService",
    "WorkerService",
    "WorkflowService",
    "ArtifactService",
    "ApprovalService",
    "PolicyService",
    "ProviderService",
    "EventService",
    "ConversationService",
    # Stream
    "EventStreamManager",
    "EventStreamConnection",
]
