from __future__ import annotations

from core.tester.contracts.applicability import (
    CategoryApplicability,
    TestApplicabilityClassifier,
    TestApplicabilityReport,
)
from core.tester.contracts.blocker import TesterBlocker
from core.tester.contracts.boundary import (
    TESTER_ALLOWED_CAPABILITIES,
    TESTER_FORBIDDEN_ACTIONS,
    TesterBoundaryGuard,
)
from core.tester.contracts.criteria import AcceptanceCriterion
from core.tester.contracts.context import (
    PresenceAssessment,
    SurfaceAssessment,
    TestContext,
    TestContextBuilder,
)
from core.tester.contracts.coverage import (
    CoverageGap,
    CriterionCoverage,
    SurfaceCoverage,
    TestCoverageEvaluator,
    TestCoverageReport,
    TestPrioritizer,
)
from core.tester.contracts.environment import TestEnvironment
from core.tester.contracts.execution import TesterExecution
from core.tester.contracts.finding import (
    AcceptanceCriterionResult,
    TesterDefect,
    TesterEvidence,
    TesterFinding,
)
from core.tester.contracts.identifiers import (
    ALL_TESTER_PREFIXES,
    BLOCKER_ID_PREFIX,
    COVERAGE_REPORT_ID_PREFIX,
    DEFECT_ID_PREFIX,
    ENVIRONMENT_ID_PREFIX,
    EVIDENCE_ID_PREFIX,
    EXECUTION_ID_PREFIX,
    FINDING_ID_PREFIX,
    GAP_ID_PREFIX,
    OBSERVATION_ID_PREFIX,
    OCR_ID_PREFIX,
    GEOMETRY_ID_PREFIX,
    FRAME_OBSERVATION_ID_PREFIX,
    OBSERVATION_SET_ID_PREFIX,
    PLAN_ID_PREFIX,
    PREFLIGHT_ID_PREFIX,
    RUNTIME_EVENT_ID_PREFIX,
    VISUAL_ASSERTION_ID_PREFIX,
    SCROLL_EVALUATION_ID_PREFIX,
    RESPONSIVE_EVALUATION_ID_PREFIX,
    TYPOGRAPHY_EVALUATION_ID_PREFIX,
    ANIMATION_EVALUATION_ID_PREFIX,
    UX_EVALUATION_ID_PREFIX,
    PERFORMANCE_MEASUREMENT_ID_PREFIX,
    LOAD_PERFORMANCE_ID_PREFIX,
    INTERACTION_PERFORMANCE_ID_PREFIX,
    NETWORK_PERFORMANCE_ID_PREFIX,
    NETWORK_REQUEST_ID_PREFIX,
    STABILITY_EVALUATION_ID_PREFIX,
    ERROR_GROUP_ID_PREFIX,
    CRASH_EVENT_ID_PREFIX,
    RECOMMENDATION_ID_PREFIX,
    RESULT_ID_PREFIX,
    RUNTIME_ID_PREFIX,
    STEP_ID_PREFIX,
    TEST_CASE_ID_PREFIX,
    ACTION_ID_PREFIX,
    SESSION_ID_PREFIX,
    TRACE_ID_PREFIX,
    VALIDATION_REPORT_ID_PREFIX,
    WORK_ORDER_ID_PREFIX,
    is_tester_id,
    new_action_id,
    new_blocker_id,
    new_coverage_report_id,
    new_defect_id,
    new_environment_id,
    new_evidence_id,
    new_execution_id,
    new_finding_id,
    new_frame_observation_id,
    new_gap_id,
    new_geometry_id,
    new_observation_id,
    new_observation_set_id,
    new_ocr_id,
    new_plan_id,
    new_preflight_id,
    new_runtime_event_id,
    new_recommendation_id,
    new_result_id,
    new_runtime_id,
    new_session_id,
    new_step_id,
    new_test_case_id,
    new_trace_id,
    new_validation_report_id,
    new_work_order_id,
    new_visual_assertion_id,
    new_scroll_evaluation_id,
    new_responsive_evaluation_id,
    new_typography_evaluation_id,
    new_animation_evaluation_id,
    new_ux_evaluation_id,
    new_performance_measurement_id,
    new_load_performance_id,
    new_interaction_performance_id,
    new_network_performance_id,
    new_network_request_id,
    new_stability_evaluation_id,
    new_error_group_id,
    new_crash_event_id,
    validate_action_id,
    validate_blocker_id,
    validate_coverage_report_id,
    validate_defect_id,
    validate_environment_id,
    validate_evidence_id,
    validate_execution_id,
    validate_finding_id,
    validate_frame_observation_id,
    validate_gap_id,
    validate_geometry_id,
    validate_observation_id,
    validate_observation_set_id,
    validate_ocr_id,
    validate_plan_id,
    validate_preflight_id,
    validate_runtime_event_id,
    validate_recommendation_id,
    validate_result_id,
    validate_runtime_id,
    validate_session_id,
    validate_step_id,
    validate_test_case_id,
    validate_trace_id,
    validate_validation_report_id,
    validate_work_order_id,
    validate_visual_assertion_id,
    validate_scroll_evaluation_id,
    validate_responsive_evaluation_id,
    validate_typography_evaluation_id,
    validate_animation_evaluation_id,
    validate_ux_evaluation_id,
    validate_performance_measurement_id,
    validate_load_performance_id,
    validate_interaction_performance_id,
    validate_network_performance_id,
    validate_network_request_id,
    validate_stability_evaluation_id,
    validate_error_group_id,
    validate_crash_event_id,
)
from core.tester.contracts.geometry import (
    GeometryObservation,
    Point,
    Rectangle,
    SpatialRelation,
    ViewportDimensions,
    VisualGeometryObserver,
)
from core.tester.contracts.observation import (
    ObservationBinder,
    TesterObservation,
)
from core.tester.contracts.ocr import (
    BoundingBox,
    MockOCRProvider,
    OCRProvider,
    OCRResult,
    TextRegion,
)
from core.tester.contracts.video_frame import (
    FrameExtractionOptions,
    FramePosition,
    VideoFrameExtractor,
    VideoFrameObservation,
)
from core.tester.contracts.observation_set import (
    ObservationAggregator,
    ObservationSet,
)
from core.tester.contracts.plan import (
    TestCase,
    TestPlan,
    TestPlanGenerator,
    TestStep,
)
from core.tester.contracts.plan_validator import (
    TestPlanValidationIssue,
    TestPlanValidationResult,
    TestPlanValidator,
)
from core.tester.contracts.planning_pipeline import TestPlanningPipeline
from core.tester.contracts.preflight import (
    ResourceCheckResult,
    RouteCheckResult,
    TestPreflightResult,
)
from core.tester.evaluator.preflight_evaluator import TestPreflightEvaluator
from core.tester.contracts.runtime_observation import RuntimeObservation
from core.tester.evaluator.runtime_evaluator import RuntimeEvaluator
from core.tester.evaluator.functional_evaluator import FunctionalAcceptanceEvaluator
from core.tester.evaluator.defect_classifier import ClassificationResult, DefectClassifier
from core.tester.contracts.observation_pipeline import TestObservationPipeline
from core.tester.contracts.action import TestActionRecord
from core.tester.contracts.browser_runtime import (
    BrowserTestRuntime,
    LocalAppTestRuntime,
)
from core.tester.contracts.functional_pipeline import (
    FunctionalEvaluationPipeline,
    TesterExecutionPipeline,
)
from core.tester.contracts.interaction import (
    InteractionEngine,
    InteractionResult,
    InteractionStatus,
    InteractionTarget,
    normalize_target,
)
from core.tester.contracts.lifecycle import TesterLifecycle
from core.tester.contracts.manager_bridge import (
    FakeTesterWorker,
    TesterManagerBridge,
)
from core.tester.contracts.navigation_policy import NavigationPolicy
from core.tester.contracts.quality_summary import QualitySummary
from core.tester.contracts.recommendation import TesterRecommendation
from core.tester.contracts.result import TesterResult
from core.tester.contracts.result_validator import TesterResultValidator
from core.tester.contracts.runtime import (
    MockTestRuntime,
    TestRuntime,
)
from core.tester.contracts.recording import (
    RecordingCaptureReason,
    ScreenRecorder,
    ScreenRecordingOptions,
    ScreenRecordingResult,
    ScreenRecordingService,
    VideoArtifactStorage,
    VideoObservation,
)
from core.tester.contracts.runtime_config import TestRuntimeConfig
from core.tester.contracts.runtime_lifecycle import TestRuntimeLifecycle
from core.tester.contracts.scope import TestScope
from core.tester.contracts.screenshot import (
    ScreenshotArtifactStorage,
    ScreenshotCaptureOptions,
    ScreenshotCaptureResult,
    ScreenshotCaptureService,
    VisualObservation,
)
from core.tester.contracts.session import (
    BrowserSession,
    HttpBrowserSession,
    MockBrowserSession,
    NavigationResult,
    PlaywrightBrowserSession,
)
from core.tester.contracts.test_case import TestCaseResult, TestStepResult
from core.tester.executor.test_case_executor import TestCaseExecutor
from core.tester.contracts.thresholds import QualityThresholds
from core.tester.contracts.trace import TesterTrace
from core.tester.contracts.validator import TesterWorkOrderValidator
from core.tester.contracts.work_order import TesterWorkOrder
from core.tester.contracts.visual import (
    VisualAssertion,
    VisualAssertionResult,
    VisualEvaluationResult,
)
from core.tester.evaluator.visual_evaluator import VisualEvaluator
from core.tester.contracts.scroll import (
    ScrollAssertion,
    ScrollBudget,
    ScrollEvaluationResult,
    ScrollPosition,
)
from core.tester.evaluator.scroll_evaluator import ScrollEvaluator
from core.tester.contracts.responsive import (
    DEFAULT_DESKTOP_PROFILE,
    DEFAULT_DESKTOP_VIEWPORT,
    DEFAULT_MOBILE_PROFILE,
    DEFAULT_MOBILE_VIEWPORT,
    DEFAULT_TABLET_PROFILE,
    DEFAULT_TABLET_VIEWPORT,
    DEFAULT_VIEWPORT_PROFILES,
    MAX_VIEWPORT_COUNT,
    ResponsiveCheck,
    ResponsiveEvaluationResult,
    ResponsiveViewportResult,
    ViewportProfile,
)
from core.tester.evaluator.responsive_evaluator import ResponsiveEvaluator
from core.tester.contracts.typography import (
    MIN_OCR_CONFIDENCE,
    TextRequirement,
    TypographyAssertion,
    TypographyAssertionResult,
    TypographyEvaluationResult,
)
from core.tester.evaluator.typography_evaluator import TypographyEvaluator
from core.tester.contracts.animation import (
    AnimationAssertion,
    AnimationAssertionResult,
    AnimationEvaluationResult,
    AnimationStateExpectation,
)
from core.tester.evaluator.animation_evaluator import AnimationEvaluator
from core.tester.contracts.ux import (
    UXFlowExpectation,
    UXAssertion,
    UXAssertionResult,
    UXEvaluationResult,
)
from core.tester.evaluator.ux_evaluator import UXFlowEvaluator
from core.tester.contracts.performance import (
    PerformanceEnvironment,
    PerformanceMeasurement,
    PerformanceMeasurementBudget,
)
from core.tester.evaluator.performance_recorder import (
    PerformanceMeasurementRecorder,
)
from core.tester.contracts.load_performance import (
    LoadPerformanceTestSpec,
    LoadPerformanceResult,
)
from core.tester.evaluator.load_performance_evaluator import (
    LoadNavigationPerformanceEvaluator,
)
from core.tester.contracts.interaction_performance import (
    InteractionPerformanceSpec,
    InteractionPerformanceResult,
)
from core.tester.evaluator.interaction_performance_evaluator import (
    InteractionPerformanceEvaluator,
)
from core.tester.contracts.network_performance import (
    NetworkRequestRecord,
    NetworkPerformanceSpec,
    NetworkPerformanceResult,
)
from core.tester.evaluator.network_performance_evaluator import (
    NetworkPerformanceEvaluator,
)
from core.tester.contracts.stability import (
    ErrorGroup,
    CrashEvent,
    StabilitySpec,
    StabilityResult,
)
from core.tester.evaluator.stability_evaluator import (
    StabilityEvaluator,
)

__all__ = [
    "AcceptanceCriterion",
    "AcceptanceCriterionResult",
    "BrowserSession",
    "BrowserTestRuntime",
    "CategoryApplicability",
    "ClassificationResult",
    "CoverageGap",
    "CriterionCoverage",
    "DefectClassifier",
    "FakeTesterWorker",
    "FunctionalAcceptanceEvaluator",
    "FunctionalEvaluationPipeline",
    "HttpBrowserSession",
    "InteractionEngine",
    "InteractionResult",
    "InteractionStatus",
    "InteractionTarget",
    "normalize_target",
    "LocalAppTestRuntime",
    "MockBrowserSession",
    "MockTestRuntime",
    "NavigationPolicy",
    "NavigationResult",
    "PlaywrightBrowserSession",
    "PresenceAssessment",
    "QualitySummary",
    "QualityThresholds",
    "RecordingCaptureReason",
    "ScreenRecorder",
    "ScreenRecordingOptions",
    "ScreenRecordingResult",
    "ScreenRecordingService",
    "ScreenshotArtifactStorage",
    "ScreenshotCaptureOptions",
    "ScreenshotCaptureResult",
    "ScreenshotCaptureService",
    "SurfaceAssessment",
    "SurfaceCoverage",
    "TestActionRecord",
    "TestApplicabilityClassifier",
    "TestApplicabilityReport",
    "TestCase",
    "TestCaseExecutor",
    "TestCaseResult",
    "TestStepResult",
    "TestContext",
    "TestContextBuilder",
    "TestCoverageEvaluator",
    "TestCoverageReport",
    "TestEnvironment",
    "TestPlan",
    "TestPlanGenerator",
    "TestPlanValidationIssue",
    "TestPlanValidationResult",
    "TestPlanValidator",
    "TestPlanningPipeline",
    "TestObservationPipeline",
    "ResourceCheckResult",
    "RouteCheckResult",
    "TestPreflightEvaluator",
    "TestPreflightResult",
    "TestPrioritizer",
    "TestRuntime",
    "TestRuntimeConfig",
    "TestRuntimeLifecycle",
    "TestScope",
    "TestStep",
    "TesterBlocker",
    "TesterBoundaryGuard",
    "TESTER_ALLOWED_CAPABILITIES",
    "TESTER_FORBIDDEN_ACTIONS",
    "TesterDefect",
    "TesterEvidence",
    "TesterExecution",
    "TesterExecutionPipeline",
    "TesterFinding",
    "TesterLifecycle",
    "TesterManagerBridge",
    "TesterRecommendation",
    "TesterResult",
    "TesterResultValidator",
    "TesterTrace",
    "TesterWorkOrder",
    "TesterWorkOrderValidator",
    "ObservationBinder",
    "TesterObservation",
    "ObservationAggregator",
    "ObservationSet",
    "BoundingBox",
    "MockOCRProvider",
    "OCRProvider",
    "OCRResult",
    "TextRegion",
    "GeometryObservation",
    "Point",
    "Rectangle",
    "SpatialRelation",
    "ViewportDimensions",
    "VisualGeometryObserver",
    "FrameExtractionOptions",
    "FramePosition",
    "VideoFrameExtractor",
    "VideoFrameObservation",
    "VideoArtifactStorage",
    "VideoObservation",
    "VisualObservation",
    "ACTION_ID_PREFIX",
    "ALL_TESTER_PREFIXES",
    "BLOCKER_ID_PREFIX",
    "COVERAGE_REPORT_ID_PREFIX",
    "DEFECT_ID_PREFIX",
    "ENVIRONMENT_ID_PREFIX",
    "EVIDENCE_ID_PREFIX",
    "EXECUTION_ID_PREFIX",
    "FINDING_ID_PREFIX",
    "FRAME_OBSERVATION_ID_PREFIX",
    "OBSERVATION_SET_ID_PREFIX",
    "GAP_ID_PREFIX",
    "OBSERVATION_ID_PREFIX",
    "OCR_ID_PREFIX",
    "GEOMETRY_ID_PREFIX",
    "PLAN_ID_PREFIX",
    "PREFLIGHT_ID_PREFIX",
    "RECOMMENDATION_ID_PREFIX",
    "RESULT_ID_PREFIX",
    "RUNTIME_ID_PREFIX",
    "SESSION_ID_PREFIX",
    "STEP_ID_PREFIX",
    "TEST_CASE_ID_PREFIX",
    "TRACE_ID_PREFIX",
    "VALIDATION_REPORT_ID_PREFIX",
    "WORK_ORDER_ID_PREFIX",
    "is_tester_id",
    "new_action_id",
    "new_blocker_id",
    "new_coverage_report_id",
    "new_defect_id",
    "new_environment_id",
    "new_evidence_id",
    "new_execution_id",
    "new_finding_id",
    "new_frame_observation_id",
    "new_gap_id",
    "new_geometry_id",
    "new_observation_id",
    "new_observation_set_id",
    "new_ocr_id",
    "new_plan_id",
    "new_preflight_id",
    "new_recommendation_id",
    "new_result_id",
    "new_runtime_id",
    "new_session_id",
    "new_step_id",
    "new_test_case_id",
    "new_trace_id",
    "new_validation_report_id",
    "new_work_order_id",
    "validate_action_id",
    "validate_blocker_id",
    "validate_coverage_report_id",
    "validate_defect_id",
    "validate_environment_id",
    "validate_evidence_id",
    "validate_execution_id",
    "validate_finding_id",
    "validate_frame_observation_id",
    "validate_gap_id",
    "validate_geometry_id",
    "validate_observation_id",
    "validate_observation_set_id",
    "validate_ocr_id",
    "validate_plan_id",
    "validate_preflight_id",
    "validate_runtime_event_id",
    "validate_recommendation_id",
    "validate_result_id",
    "validate_runtime_id",
    "validate_session_id",
    "validate_step_id",
    "validate_test_case_id",
    "validate_trace_id",
    "validate_validation_report_id",
    "validate_work_order_id",
    "RUNTIME_EVENT_ID_PREFIX",
    "new_runtime_event_id",
    "RuntimeObservation",
    "RuntimeEvaluator",
    "VISUAL_ASSERTION_ID_PREFIX",
    "new_visual_assertion_id",
    "validate_visual_assertion_id",
    "VisualAssertion",
    "VisualAssertionResult",
    "VisualEvaluationResult",
    "VisualEvaluator",
    "SCROLL_EVALUATION_ID_PREFIX",
    "new_scroll_evaluation_id",
    "validate_scroll_evaluation_id",
    "ScrollPosition",
    "ScrollBudget",
    "ScrollAssertion",
    "ScrollEvaluationResult",
    "ScrollEvaluator",
    "RESPONSIVE_EVALUATION_ID_PREFIX",
    "new_responsive_evaluation_id",
    "validate_responsive_evaluation_id",
    "DEFAULT_DESKTOP_PROFILE",
    "DEFAULT_DESKTOP_VIEWPORT",
    "DEFAULT_MOBILE_PROFILE",
    "DEFAULT_MOBILE_VIEWPORT",
    "DEFAULT_TABLET_PROFILE",
    "DEFAULT_TABLET_VIEWPORT",
    "DEFAULT_VIEWPORT_PROFILES",
    "MAX_VIEWPORT_COUNT",
    "ResponsiveCheck",
    "ResponsiveEvaluationResult",
    "ResponsiveViewportResult",
    "ViewportProfile",
    "ResponsiveEvaluator",
    "TYPOGRAPHY_EVALUATION_ID_PREFIX",
    "new_typography_evaluation_id",
    "validate_typography_evaluation_id",
    "MIN_OCR_CONFIDENCE",
    "TextRequirement",
    "TypographyAssertion",
    "TypographyAssertionResult",
    "TypographyEvaluationResult",
    "TypographyEvaluator",
    "ANIMATION_EVALUATION_ID_PREFIX",
    "new_animation_evaluation_id",
    "validate_animation_evaluation_id",
    "AnimationAssertion",
    "AnimationAssertionResult",
    "AnimationEvaluationResult",
    "AnimationStateExpectation",
    "AnimationEvaluator",
    "UX_EVALUATION_ID_PREFIX",
    "new_ux_evaluation_id",
    "validate_ux_evaluation_id",
    "UXFlowExpectation",
    "UXAssertion",
    "UXAssertionResult",
    "UXEvaluationResult",
    "UXFlowEvaluator",
    "PERFORMANCE_MEASUREMENT_ID_PREFIX",
    "new_performance_measurement_id",
    "validate_performance_measurement_id",
    "PerformanceEnvironment",
    "PerformanceMeasurementBudget",
    "PerformanceMeasurement",
    "PerformanceMeasurementRecorder",
    "LOAD_PERFORMANCE_ID_PREFIX",
    "new_load_performance_id",
    "validate_load_performance_id",
    "LoadPerformanceTestSpec",
    "LoadPerformanceResult",
    "LoadNavigationPerformanceEvaluator",
    "INTERACTION_PERFORMANCE_ID_PREFIX",
    "new_interaction_performance_id",
    "validate_interaction_performance_id",
    "InteractionPerformanceSpec",
    "InteractionPerformanceResult",
    "InteractionPerformanceEvaluator",
    "NETWORK_PERFORMANCE_ID_PREFIX",
    "NETWORK_REQUEST_ID_PREFIX",
    "new_network_performance_id",
    "validate_network_performance_id",
    "new_network_request_id",
    "validate_network_request_id",
    "NetworkRequestRecord",
    "NetworkPerformanceSpec",
    "NetworkPerformanceResult",
    "NetworkPerformanceEvaluator",
    "STABILITY_EVALUATION_ID_PREFIX",
    "ERROR_GROUP_ID_PREFIX",
    "CRASH_EVENT_ID_PREFIX",
    "new_stability_evaluation_id",
    "validate_stability_evaluation_id",
    "new_error_group_id",
    "validate_error_group_id",
    "new_crash_event_id",
    "validate_crash_event_id",
    "ErrorGroup",
    "CrashEvent",
    "StabilitySpec",
    "StabilityResult",
    "StabilityEvaluator",
]

