from __future__ import annotations

from core.tester.contracts.applicability import (
    CategoryApplicability,
    TestApplicabilityClassifier,
    TestApplicabilityReport,
)
from core.tester.contracts.blocker import TesterBlocker
from core.tester.contracts.boundary import (
    TESTER_ALLOWED_CAPABILITIES,
    TESTER_FORBIDDEN_ACTIONS,
    TesterBoundaryGuard,
)
from core.tester.contracts.criteria import AcceptanceCriterion
from core.tester.contracts.context import (
    PresenceAssessment,
    SurfaceAssessment,
    TestContext,
    TestContextBuilder,
)
from core.tester.contracts.coverage import (
    CoverageGap,
    CriterionCoverage,
    SurfaceCoverage,
    TestCoverageEvaluator,
    TestCoverageReport,
    TestPrioritizer,
)
from core.tester.contracts.environment import TestEnvironment
from core.tester.contracts.execution import TesterExecution
from core.tester.contracts.finding import (
    AcceptanceCriterionResult,
    TesterDefect,
    TesterEvidence,
    TesterFinding,
)
from core.tester.contracts.identifiers import (
    ALL_TESTER_PREFIXES,
    BLOCKER_ID_PREFIX,
    COVERAGE_REPORT_ID_PREFIX,
    DEFECT_ID_PREFIX,
    ENVIRONMENT_ID_PREFIX,
    EVIDENCE_ID_PREFIX,
    EXECUTION_ID_PREFIX,
    FINDING_ID_PREFIX,
    GAP_ID_PREFIX,
    PLAN_ID_PREFIX,
    RECOMMENDATION_ID_PREFIX,
    RESULT_ID_PREFIX,
    RUNTIME_ID_PREFIX,
    STEP_ID_PREFIX,
    TEST_CASE_ID_PREFIX,
    ACTION_ID_PREFIX,
    SESSION_ID_PREFIX,
    TRACE_ID_PREFIX,
    VALIDATION_REPORT_ID_PREFIX,
    WORK_ORDER_ID_PREFIX,
    is_tester_id,
    new_action_id,
    new_blocker_id,
    new_coverage_report_id,
    new_defect_id,
    new_environment_id,
    new_evidence_id,
    new_execution_id,
    new_finding_id,
    new_gap_id,
    new_plan_id,
    new_recommendation_id,
    new_result_id,
    new_runtime_id,
    new_session_id,
    new_step_id,
    new_test_case_id,
    new_trace_id,
    new_validation_report_id,
    new_work_order_id,
    validate_action_id,
    validate_blocker_id,
    validate_coverage_report_id,
    validate_defect_id,
    validate_environment_id,
    validate_evidence_id,
    validate_execution_id,
    validate_finding_id,
    validate_gap_id,
    validate_plan_id,
    validate_recommendation_id,
    validate_result_id,
    validate_runtime_id,
    validate_session_id,
    validate_step_id,
    validate_test_case_id,
    validate_trace_id,
    validate_validation_report_id,
    validate_work_order_id,
)
from core.tester.contracts.plan import (
    TestCase,
    TestPlan,
    TestPlanGenerator,
    TestStep,
)
from core.tester.contracts.plan_validator import (
    TestPlanValidationIssue,
    TestPlanValidationResult,
    TestPlanValidator,
)
from core.tester.contracts.planning_pipeline import TestPlanningPipeline
from core.tester.contracts.action import TestActionRecord
from core.tester.contracts.browser_runtime import (
    BrowserTestRuntime,
    LocalAppTestRuntime,
)
from core.tester.contracts.interaction import (
    InteractionEngine,
    InteractionResult,
    InteractionStatus,
    InteractionTarget,
    normalize_target,
)
from core.tester.contracts.lifecycle import TesterLifecycle
from core.tester.contracts.manager_bridge import (
    FakeTesterWorker,
    TesterManagerBridge,
)
from core.tester.contracts.navigation_policy import NavigationPolicy
from core.tester.contracts.quality_summary import QualitySummary
from core.tester.contracts.recommendation import TesterRecommendation
from core.tester.contracts.result import TesterResult
from core.tester.contracts.result_validator import TesterResultValidator
from core.tester.contracts.runtime import (
    MockTestRuntime,
    TestRuntime,
)
from core.tester.contracts.recording import (
    RecordingCaptureReason,
    ScreenRecorder,
    ScreenRecordingOptions,
    ScreenRecordingResult,
    ScreenRecordingService,
    VideoArtifactStorage,
    VideoObservation,
)
from core.tester.contracts.runtime_config import TestRuntimeConfig
from core.tester.contracts.runtime_lifecycle import TestRuntimeLifecycle
from core.tester.contracts.scope import TestScope
from core.tester.contracts.screenshot import (
    ScreenshotArtifactStorage,
    ScreenshotCaptureOptions,
    ScreenshotCaptureResult,
    ScreenshotCaptureService,
    VisualObservation,
)
from core.tester.contracts.session import (
    BrowserSession,
    HttpBrowserSession,
    MockBrowserSession,
    NavigationResult,
    PlaywrightBrowserSession,
)
from core.tester.contracts.test_case import TestCaseResult
from core.tester.contracts.thresholds import QualityThresholds
from core.tester.contracts.trace import TesterTrace
from core.tester.contracts.validator import TesterWorkOrderValidator
from core.tester.contracts.work_order import TesterWorkOrder

__all__ = [
    "AcceptanceCriterion",
    "AcceptanceCriterionResult",
    "BrowserSession",
    "BrowserTestRuntime",
    "CategoryApplicability",
    "CoverageGap",
    "CriterionCoverage",
    "FakeTesterWorker",
    "HttpBrowserSession",
    "InteractionEngine",
    "InteractionResult",
    "InteractionStatus",
    "InteractionTarget",
    "normalize_target",
    "LocalAppTestRuntime",
    "MockBrowserSession",
    "MockTestRuntime",
    "NavigationPolicy",
    "NavigationResult",
    "PlaywrightBrowserSession",
    "PresenceAssessment",
    "QualitySummary",
    "QualityThresholds",
    "RecordingCaptureReason",
    "ScreenRecorder",
    "ScreenRecordingOptions",
    "ScreenRecordingResult",
    "ScreenRecordingService",
    "ScreenshotArtifactStorage",
    "ScreenshotCaptureOptions",
    "ScreenshotCaptureResult",
    "ScreenshotCaptureService",
    "SurfaceAssessment",
    "SurfaceCoverage",
    "TestActionRecord",
    "TestApplicabilityClassifier",
    "TestApplicabilityReport",
    "TestCase",
    "TestCaseResult",
    "TestContext",
    "TestContextBuilder",
    "TestCoverageEvaluator",
    "TestCoverageReport",
    "TestEnvironment",
    "TestPlan",
    "TestPlanGenerator",
    "TestPlanValidationIssue",
    "TestPlanValidationResult",
    "TestPlanValidator",
    "TestPlanningPipeline",
    "TestPrioritizer",
    "TestRuntime",
    "TestRuntimeConfig",
    "TestRuntimeLifecycle",
    "TestScope",
    "TestStep",
    "TesterBlocker",
    "TesterBoundaryGuard",
    "TESTER_ALLOWED_CAPABILITIES",
    "TESTER_FORBIDDEN_ACTIONS",
    "TesterDefect",
    "TesterEvidence",
    "TesterExecution",
    "TesterFinding",
    "TesterLifecycle",
    "TesterManagerBridge",
    "TesterRecommendation",
    "TesterResult",
    "TesterResultValidator",
    "TesterTrace",
    "TesterWorkOrder",
    "TesterWorkOrderValidator",
    "VideoArtifactStorage",
    "VideoObservation",
    "VisualObservation",
    "ACTION_ID_PREFIX",
    "ALL_TESTER_PREFIXES",
    "BLOCKER_ID_PREFIX",
    "COVERAGE_REPORT_ID_PREFIX",
    "DEFECT_ID_PREFIX",
    "ENVIRONMENT_ID_PREFIX",
    "EVIDENCE_ID_PREFIX",
    "EXECUTION_ID_PREFIX",
    "FINDING_ID_PREFIX",
    "GAP_ID_PREFIX",
    "PLAN_ID_PREFIX",
    "RECOMMENDATION_ID_PREFIX",
    "RESULT_ID_PREFIX",
    "RUNTIME_ID_PREFIX",
    "SESSION_ID_PREFIX",
    "STEP_ID_PREFIX",
    "TEST_CASE_ID_PREFIX",
    "TRACE_ID_PREFIX",
    "VALIDATION_REPORT_ID_PREFIX",
    "WORK_ORDER_ID_PREFIX",
    "is_tester_id",
    "new_action_id",
    "new_blocker_id",
    "new_coverage_report_id",
    "new_defect_id",
    "new_environment_id",
    "new_evidence_id",
    "new_execution_id",
    "new_finding_id",
    "new_gap_id",
    "new_plan_id",
    "new_recommendation_id",
    "new_result_id",
    "new_runtime_id",
    "new_session_id",
    "new_step_id",
    "new_test_case_id",
    "new_trace_id",
    "new_validation_report_id",
    "new_work_order_id",
    "validate_action_id",
    "validate_blocker_id",
    "validate_coverage_report_id",
    "validate_defect_id",
    "validate_environment_id",
    "validate_evidence_id",
    "validate_execution_id",
    "validate_finding_id",
    "validate_gap_id",
    "validate_plan_id",
    "validate_recommendation_id",
    "validate_result_id",
    "validate_runtime_id",
    "validate_session_id",
    "validate_step_id",
    "validate_test_case_id",
    "validate_trace_id",
    "validate_validation_report_id",
    "validate_work_order_id",
]
