from __future__ import annotations

from core.research.contracts.crawler_report import CrawlerReport, RawSourceReference
from core.research.contracts.crawler_task import CrawlerTask
from core.research.contracts.evidence import (
    EvidenceItem,
    EvidenceProvenance,
    Source,
    compute_sha256,
)
from core.research.contracts.intent import (
    Ambiguity,
    ClarificationQuestion,
    EvidenceRequirement,
    IntentConfidence,
    ResearchIntent,
    TemporalScope,
    VersionScope,
)
from core.research.contracts.plan import ResearchPlan
from core.research.contracts.question import ResearchQuestion
from core.research.contracts.request import ResearchRequest, ResearchScope
from core.research.contracts.result import (
    ResearchContradiction,
    ResearchFinding,
    ResearchKnowledgeGap,
    ResearchRecommendation,
    ResearchResult,
)
from core.research.crawler.base import BaseCrawler
from core.research.crawler.capability import CrawlerCapabilitySpec, matches_capability
from core.research.crawler.community import CommunityCrawler
from core.research.crawler.documentation import DocumentationCrawler
from core.research.crawler.lifecycle import CrawlerStateMachine
from core.research.crawler.mock_crawler import MockCrawler
from core.research.crawler.registry import CrawlerRegistry
from core.research.crawler.project_context import ProjectContextCrawler
from core.research.crawler.repository import RepositoryCrawler
from core.research.crawler.structured import StructuredDataCrawler
from core.research.crawler.web_fetch import WebFetchCrawler
from core.research.crawler.web_search import WebSearchCrawler
from core.research.errors import (
    CrawlerExecutionError,
    CrawlerNotFoundError,
    CrawlerTaskNotFoundError,
    InsufficientEvidenceError,
    InvalidStateTransitionError,
    ProvenanceError,
    StructuredDataAuthenticationError,
    StructuredDataCancelledError,
    StructuredDataError,
    StructuredDataLimitError,
    StructuredDataLocationError,
    StructuredDataMalformedResponseError,
    StructuredDataNotFoundError,
    StructuredDataProviderError,
    StructuredDataRateLimitError,
    StructuredDataSecurityError,
    StructuredDataPolicyViolationError,
    StructuredDataTimeoutError,
    StructuredDataValidationError,
)
from core.research.evidence.collector import EvidenceCollector
from core.research.evidence.evaluator import EvidenceEvaluator
from core.research.orchestration.spawner import CrawlerSpawner
from core.research.orchestration.supervisor import CrawlerSupervisor
from core.research.planning.decomposer import ResearchDecomposer
from core.research.planning.extractor import (
    DeterministicRequestExtractor,
    ExtractedRequestElements,
    ExtractionProvenance,
    ExtractionUncertainty,
)
from core.research.planning.intent_classifier import (
    DeterministicIntentClassifier,
    IntentClassificationResult,
    IntentSignal,
)
from core.research.planning.normalizer import (
    NormalizedResearchRequest,
    ResearchRequestNormalizer,
)
from core.research.planning.task_generator import CrawlerTaskGenerator
from core.research.planning.understanding_engine import (
    LLMUnderstandingEngine,
    ProposalValidationResult,
    ProposalValidator,
    ResearchIntentProposal,
    UnderstandingError,
)
from core.research.planning.understanding_orchestrator import (
    RequestUnderstandingOrchestrator,
    RequestUnderstandingResult,
    UnderstandingProvenance,
)
from core.routing import (
    RequestDispatcher,
    RequestRouter,
    RouteDestination,
    RoutingDecision,
)
from core.research.researcher import Researcher
from core.research.state.lifecycle import ResearchStateMachine
from core.research.state.model import ResearchState, StateTransitionRecord
from core.research.synthesis.synthesizer import ResearchSynthesizer
from core.research.structured import (
    BoundedRetrievalLimits,
    FakeStructuredDataProvider,
    FieldSegment,
    HttpMethod,
    IndexSegment,
    PaginatedRetrievalResult,
    PaginationConfig,
    PaginationMetadata,
    PaginationType,
    ParsedStructuredData,
    PathSegment,
    RetrievalStatus,
    SchemaField,
    SchemaStructureType,
    SourceLocation,
    StructuredContentType,
    StructuredDataLimits,
    StructuredDataPaginator,
    StructuredDataProvider,
    StructuredDataRequest,
    StructuredDataRequestBuilder,
    StructuredDataSecurityPolicy,
    StructuredDataResponse,
    StructuredDataSource,
    StructuredDataType,
    StructuredRecord,
    StructuredResponseParser,
    extract_pagination_metadata,
    parse_link_header,
    StructuredSchema,
    StructuredSourceType,
    WildcardSegment,
    canonical_json_dumps,
    compute_structured_hash,
    FilterOperator,
    OrderDirection,
    QueryFilter,
    QueryOrder,
    StructuredQuery,
    QueryResult,
    LocalStructuredQueryEngine,
    RemoteQueryContract,
    RemoteQueryMapper,
    CredentialType,
    CredentialReference,
    ResolvedCredentials,
    CredentialResolver,
    CredentialRedactor,
    RateLimitConfig,
    RateLimitedStructuredDataProvider,
    parse_retry_after,
)
from core.research.errors import (
    StructuredDataQueryError,
    StructuredDataInvalidFilterError,
    StructuredDataInvalidOperatorError,
    StructuredDataInvalidFieldError,
    StructuredDataAuthorizationError,
    StructuredDataQuotaExceededError,
    ProjectContextError,
    ProjectValidationError,
    ProjectSecurityError,
    ProjectNotFoundError,
    ProjectProviderError,
    ProjectFileNotFoundError,
    ProjectAccessError,
    ProjectMalformedFileError,
    ProjectResourceLimitError,
    ProjectTimeoutError,
    ProjectCancelledError,
)
from core.research.project import (
    ProjectType,
    ProjectConfigType,
    ProjectDependencyType,
    ProjectVCSState,
    ProjectIdentity,
    ProjectDirectory,
    ProjectStructure,
    ProjectFile,
    ProjectSourceMaterial,
    ProjectSymbol,
    ProjectConfigurationMetadata,
    ProjectDependencyMetadata,
    ProjectVCSContext,
    ProjectContext,
    normalize_project_path,
    mask_sensitive_config,
    ProjectFetchLimits,
    ProjectTreeParams,
    ProjectFileParams,
    ProjectWorkspaceProvider,
    FakeProjectWorkspaceProvider,
    LocalProjectWorkspaceProvider,
    ProjectDiscoveryOptions,
    DiscoveredProjectStructure,
    ProjectStructureDiscoverer,
    is_manifest_path,
    classify_manifest_ecosystem,
    is_test_file_path,
    is_documentation_file_path,
    is_generated_file_path,
    detect_source_roots,
    # Selection Engine (Part 8.4)
    CandidateProjectFile,
    ProjectSelectionQuery,
    ProjectSelectionOptions,
    ProjectRelevanceScorer,
    SelectedProjectContext,
    ProjectContextSelector,
    classify_project_file_category,
    # Source & Contract Extraction (Part 8.5)
    ProjectContractType,
    ProjectContract,
    ProjectDocSection,
    ProjectDocumentationMetadata,
    ProjectExtractionOptions,
    ExtractedProjectFile,
    ProjectContractClassifier,
    ProjectSourceExtractor,
    # Documentation, Config & Dependencies Extraction (Part 8.6)
    ProjectDocumentationExtractor,
    ProjectConfigurationExtractor,
    ProjectDependencyExtractor,
    ProjectContextExtractor,
    # VCS & Workspace State Inspection (Part 8.7)
    ProjectVCSOptions,
    ProjectVCSInspector,
)
from core.research.types import (
    CrawlerCapability,
    CrawlerHealthStatus,
    CrawlerReportStatus,
    CrawlerStatus,
    CrawlerTaskStatus,
    DesiredOutput,
    EvidenceSufficiency,
    FactClassification,
    FreshnessRequirement,
    IntentType,
    ResearchConfidence,
    ResearchLifecycleState,
    ResearchMode,
    ResearchQuestionStatus,
    ResearchResultStatus,
    SourceType,
    UnderstandingStatus,
)

__all__ = [
    # Lifecycle & Types
    "ResearchLifecycleState",
    "CrawlerStatus",
    "CrawlerHealthStatus",
    "CrawlerCapability",
    "CrawlerTaskStatus",
    "CrawlerReportStatus",
    "ResearchMode",
    "FactClassification",
    "ResearchConfidence",
    "ResearchQuestionStatus",
    "EvidenceSufficiency",
    "ResearchResultStatus",
    "SourceType",
    "IntentType",
    "FreshnessRequirement",
    "DesiredOutput",
    "UnderstandingStatus",
    # Contracts
    "ResearchRequest",
    "ResearchScope",
    "ResearchQuestion",
    "ResearchPlan",
    "CrawlerTask",
    "CrawlerReport",
    "RawSourceReference",
    "EvidenceItem",
    "EvidenceProvenance",
    "Source",
    "compute_sha256",
    "ResearchFinding",
    "ResearchContradiction",
    "ResearchKnowledgeGap",
    "ResearchRecommendation",
    "ResearchResult",
    "ResearchIntent",
    "IntentConfidence",
    "Ambiguity",
    "ClarificationQuestion",
    "TemporalScope",
    "VersionScope",
    "EvidenceRequirement",
    # Errors
    "ResearchError",
    "InvalidStateTransitionError",
    "InsufficientEvidenceError",
    "CrawlerExecutionError",
    "CrawlerNotFoundError",
    "CrawlerTaskNotFoundError",
    "ProvenanceError",
    # State
    "ResearchStateMachine",
    "ResearchState",
    "StateTransitionRecord",
    # Crawler
    "BaseCrawler",
    "CrawlerStateMachine",
    "CrawlerCapabilitySpec",
    "matches_capability",
    "CrawlerRegistry",
    "MockCrawler",
    "WebSearchCrawler",
    "DocumentationCrawler",
    "RepositoryCrawler",
    "CommunityCrawler",
    # Planning
    "ResearchDecomposer",
    "CrawlerTaskGenerator",
    "ResearchRequestNormalizer",
    "NormalizedResearchRequest",
    "IntentSignal",
    "IntentClassificationResult",
    "DeterministicIntentClassifier",
    "ExtractionProvenance",
    "ExtractionUncertainty",
    "ExtractedRequestElements",
    "DeterministicRequestExtractor",
    "ResearchIntentProposal",
    "ProposalValidationResult",
    "ProposalValidator",
    "LLMUnderstandingEngine",
    "UnderstandingError",
    "UnderstandingProvenance",
    "RequestUnderstandingResult",
    "RequestUnderstandingOrchestrator",
    # Intelligent Request Routing (Part 1.7)
    "RouteDestination",
    "RoutingDecision",
    "RequestRouter",
    "RequestDispatcher",
    # Evidence
    "EvidenceCollector",
    "EvidenceEvaluator",
    # Orchestration
    "CrawlerSpawner",
    "CrawlerSupervisor",
    # Synthesis
    "ResearchSynthesizer",
    # Coordinator
    "Researcher",
    # Structured Data (Part 7)
    "StructuredDataProvider",
    "FakeStructuredDataProvider",
    "FieldSegment",
    "HttpMethod",
    "IndexSegment",
    "BoundedRetrievalLimits",
    "PaginatedRetrievalResult",
    "PaginationConfig",
    "PaginationMetadata",
    "PaginationType",
    "ParsedStructuredData",
    "PathSegment",
    "RetrievalStatus",
    "SchemaField",
    "SchemaStructureType",
    "SourceLocation",
    "StructuredContentType",
    "StructuredDataLimits",
    "StructuredDataPaginator",
    "StructuredDataRequest",
    "StructuredDataRequestBuilder",
    "StructuredDataSecurityPolicy",
    "StructuredDataResponse",
    "StructuredDataSource",
    "StructuredDataType",
    "StructuredRecord",
    "StructuredResponseParser",
    "StructuredSchema",
    "StructuredSourceType",
    "WildcardSegment",
    "canonical_json_dumps",
    "compute_structured_hash",
    "StructuredDataAuthenticationError",
    "StructuredDataCancelledError",
    "StructuredDataError",
    "StructuredDataLimitError",
    "StructuredDataLocationError",
    "StructuredDataMalformedResponseError",
    "StructuredDataNotFoundError",
    "StructuredDataProviderError",
    "StructuredDataRateLimitError",
    "StructuredDataSecurityError",
    "StructuredDataPolicyViolationError",
    "StructuredDataTimeoutError",
    "StructuredDataValidationError",
    "FilterOperator",
    "OrderDirection",
    "QueryFilter",
    "QueryOrder",
    "StructuredQuery",
    "QueryResult",
    "LocalStructuredQueryEngine",
    "RemoteQueryContract",
    "RemoteQueryMapper",
    "StructuredDataQueryError",
    "StructuredDataInvalidFilterError",
    "StructuredDataInvalidOperatorError",
    "StructuredDataInvalidFieldError",
    "StructuredDataAuthorizationError",
    "StructuredDataQuotaExceededError",
    "CredentialType",
    "CredentialReference",
    "ResolvedCredentials",
    "CredentialResolver",
    "CredentialRedactor",
    "RateLimitConfig",
    "RateLimitedStructuredDataProvider",
    "parse_retry_after",
    "StructuredDataCrawler",
    # Project Context (Part 8.1 & 8.2)
    "ProjectType",
    "ProjectConfigType",
    "ProjectDependencyType",
    "ProjectVCSState",
    "ProjectIdentity",
    "ProjectDirectory",
    "ProjectStructure",
    "ProjectFile",
    "ProjectSourceMaterial",
    "ProjectSymbol",
    "ProjectConfigurationMetadata",
    "ProjectDependencyMetadata",
    "ProjectVCSContext",
    "ProjectContext",
    "normalize_project_path",
    "mask_sensitive_config",
    "ProjectContextError",
    "ProjectValidationError",
    "ProjectSecurityError",
    "ProjectNotFoundError",
    "ProjectProviderError",
    "ProjectFileNotFoundError",
    "ProjectAccessError",
    "ProjectMalformedFileError",
    "ProjectResourceLimitError",
    "ProjectTimeoutError",
    "ProjectCancelledError",
    "ProjectFetchLimits",
    "ProjectTreeParams",
    "ProjectFileParams",
    "ProjectWorkspaceProvider",
    "FakeProjectWorkspaceProvider",
    "LocalProjectWorkspaceProvider",
    # Project Structure Discovery (Part 8.3)
    "ProjectDiscoveryOptions",
    "DiscoveredProjectStructure",
    "ProjectStructureDiscoverer",
    "is_manifest_path",
    "classify_manifest_ecosystem",
    "is_test_file_path",
    "is_documentation_file_path",
    "is_generated_file_path",
    "detect_source_roots",
    # Selection Engine (Part 8.4)
    "CandidateProjectFile",
    "ProjectSelectionQuery",
    "ProjectSelectionOptions",
    "ProjectRelevanceScorer",
    "SelectedProjectContext",
    "ProjectContextSelector",
    "classify_project_file_category",
    # Source & Contract Extraction (Part 8.5)
    "ProjectContractType",
    "ProjectContract",
    "ProjectDocSection",
    "ProjectDocumentationMetadata",
    "ProjectExtractionOptions",
    "ExtractedProjectFile",
    "ProjectContractClassifier",
    "ProjectSourceExtractor",
    # Documentation, Config & Dependencies Extraction (Part 8.6)
    "ProjectDocumentationExtractor",
    "ProjectConfigurationExtractor",
    "ProjectDependencyExtractor",
    "ProjectContextExtractor",
    # VCS & Workspace State Inspection (Part 8.7)
    "ProjectVCSOptions",
    "ProjectVCSInspector",
    # Crawler Worker (Part 8.8)
    "ProjectContextCrawler",
]
