from enum import Enum


class EventType(str, Enum):
    """Authoritative taxonomy of events in the AutonomOS runtime."""

    # Project Events
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_DELETED = "PROJECT_DELETED"

    # Worker Events
    WORKER_ACTIVATION_REQUESTED = "WORKER_ACTIVATION_REQUESTED"
    WORKER_ACTIVATION_STARTED = "WORKER_ACTIVATION_STARTED"
    WORKER_ACTIVATION_COMPLETED = "WORKER_ACTIVATION_COMPLETED"
    WORKER_ACTIVATION_FAILED = "WORKER_ACTIVATION_FAILED"
    WORKER_REGISTERED = "WORKER_REGISTERED"
    WORKER_UPDATED = "WORKER_UPDATED"
    WORKER_ASSIGNED = "WORKER_ASSIGNED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_REPORTING = "WORKER_REPORTING"
    WORKER_FINISHED = "WORKER_FINISHED"
    WORKER_FAILED = "WORKER_FAILED"
    WORKER_BECAME_IDLE = "WORKER_BECAME_IDLE"
    WORKER_REMOVED = "WORKER_REMOVED"

    # Task Events
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_READY = "TASK_READY"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STARTED = "TASK_STARTED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_RETRYING = "TASK_RETRYING"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"

    # Dependency Events
    DEPENDENCY_ADDED = "DEPENDENCY_ADDED"
    DEPENDENCY_REMOVED = "DEPENDENCY_REMOVED"
    DEPENDENCY_SATISFIED = "DEPENDENCY_SATISFIED"
    DEPENDENCY_CYCLE_DETECTED = "DEPENDENCY_CYCLE_DETECTED"

    # Artifact Events
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    ARTIFACT_UPDATED = "ARTIFACT_UPDATED"
    ARTIFACT_DELETED = "ARTIFACT_DELETED"

    # Evidence & Governance Events
    EVIDENCE_RECORDED = "EVIDENCE_RECORDED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_RESOLVED = "APPROVAL_RESOLVED"

    # Memory & Knowledge Events (Stage 3)
    MEMORY_CREATED = "MEMORY_CREATED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    MEMORY_DELETED = "MEMORY_DELETED"
    DECISION_CREATED = "DECISION_CREATED"
    REPORT_CREATED = "REPORT_CREATED"
    ISSUE_RECORDED = "ISSUE_RECORDED"
    ISSUE_UPDATED = "ISSUE_UPDATED"

    # Context Engine Events (Stage 4)
    CONTEXT_REQUESTED = "CONTEXT_REQUESTED"
    CONTEXT_ASSEMBLED = "CONTEXT_ASSEMBLED"
    CONTEXT_WARNING = "CONTEXT_WARNING"

    # Tool Runtime Events (Stage 5)
    TOOL_REQUESTED = "TOOL_REQUESTED"
    TOOL_AUTHORIZED = "TOOL_AUTHORIZED"
    TOOL_DENIED = "TOOL_DENIED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    TOOL_TIMED_OUT = "TOOL_TIMED_OUT"

    # Safety, Checkpoints & Rollback Events (Stage 6)
    SAFETY_CHECK_REQUESTED = "SAFETY_CHECK_REQUESTED"
    SAFETY_ALLOWED = "SAFETY_ALLOWED"
    SAFETY_DENIED = "SAFETY_DENIED"
    SAFETY_ESCALATED = "SAFETY_ESCALATED"
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    CHECKPOINT_COMMITTED = "CHECKPOINT_COMMITTED"
    CHECKPOINT_ROLLBACK_STARTED = "CHECKPOINT_ROLLBACK_STARTED"
    CHECKPOINT_ROLLBACK_COMPLETED = "CHECKPOINT_ROLLBACK_COMPLETED"
    CHECKPOINT_ROLLBACK_FAILED = "CHECKPOINT_ROLLBACK_FAILED"
    SCOPE_DEVIATION_DETECTED = "SCOPE_DEVIATION_DETECTED"

    # Verification & Evidence Events (Stage 7)
    VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    CHECK_STARTED = "CHECK_STARTED"
    CHECK_PASSED = "CHECK_PASSED"
    CHECK_FAILED = "CHECK_FAILED"
    CHECK_UNCERTAIN = "CHECK_UNCERTAIN"
    CHECK_ERROR = "CHECK_ERROR"
    VERIFICATION_PASSED = "VERIFICATION_PASSED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    VERIFICATION_UNCERTAIN = "VERIFICATION_UNCERTAIN"

    # Inference Gateway & OmniRoute Events (Stage 8)
    INFERENCE_REQUESTED = "INFERENCE_REQUESTED"
    INFERENCE_ROUTING_STARTED = "INFERENCE_ROUTING_STARTED"
    INFERENCE_ROUTED = "INFERENCE_ROUTED"
    INFERENCE_STARTED = "INFERENCE_STARTED"
    INFERENCE_COMPLETED = "INFERENCE_COMPLETED"
    INFERENCE_FAILED = "INFERENCE_FAILED"
    INFERENCE_RETRIED = "INFERENCE_RETRIED"
    INFERENCE_FALLBACK = "INFERENCE_FALLBACK"
    INFERENCE_CANCELLED = "INFERENCE_CANCELLED"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"

    # Worker-Emitted Information (Explicitly non-authoritative worker self-reports)
    WORKER_PROGRESS_LOGGED = "WORKER_PROGRESS_LOGGED"
    WORKER_OUTPUT_PRODUCED = "WORKER_OUTPUT_PRODUCED"

    # Manager & Workforce Orchestration Events (Stage 10)
    MANAGER_CYCLE_STARTED = "MANAGER_CYCLE_STARTED"
    MANAGER_CONTEXT_BUILT = "MANAGER_CONTEXT_BUILT"
    MANAGER_DECISION_CREATED = "MANAGER_DECISION_CREATED"
    MANAGER_ACTION_ACCEPTED = "MANAGER_ACTION_ACCEPTED"
    MANAGER_ACTION_REJECTED = "MANAGER_ACTION_REJECTED"
    MANAGER_PLAN_CREATED = "MANAGER_PLAN_CREATED"
    MANAGER_PLAN_UPDATED = "MANAGER_PLAN_UPDATED"
    MANAGER_REPLAN = "MANAGER_REPLAN"
    MANAGER_WAITING = "MANAGER_WAITING"
    MANAGER_ESCALATED = "MANAGER_ESCALATED"
    MANAGER_USER_INPUT_REQUIRED = "MANAGER_USER_INPUT_REQUIRED"
    MANAGER_CYCLE_COMPLETED = "MANAGER_CYCLE_COMPLETED"
    MANAGER_CYCLE_FAILED = "MANAGER_CYCLE_FAILED"
    MANAGER_STAGNATION_DETECTED = "MANAGER_STAGNATION_DETECTED"

    # Researcher Specialist Worker Events (Stage 11)
    RESEARCH_STARTED = "RESEARCH_STARTED"
    RESEARCH_PLAN_CREATED = "RESEARCH_PLAN_CREATED"
    RESEARCH_SEARCH_PERFORMED = "RESEARCH_SEARCH_PERFORMED"
    RESEARCH_SOURCE_FETCHED = "RESEARCH_SOURCE_FETCHED"
    RESEARCH_FINDING_CREATED = "RESEARCH_FINDING_CREATED"
    RESEARCH_CONTRADICTION_DETECTED = "RESEARCH_CONTRADICTION_DETECTED"
    RESEARCH_KNOWLEDGE_GAP = "RESEARCH_KNOWLEDGE_GAP"
    RESEARCH_COMPLETED = "RESEARCH_COMPLETED"
    RESEARCH_FAILED = "RESEARCH_FAILED"

    # Programmer Specialist Worker Events (Stage 12)
    PROGRAMMER_REQUESTED = "PROGRAMMER_REQUESTED"
    PROGRAMMER_STARTED = "PROGRAMMER_STARTED"
    PROGRAMMER_PLAN_CREATED = "PROGRAMMER_PLAN_CREATED"
    PROGRAMMER_INSPECTION_PERFORMED = "PROGRAMMER_INSPECTION_PERFORMED"
    PROGRAMMER_CODE_MODIFIED = "PROGRAMMER_CODE_MODIFIED"
    PROGRAMMER_DIFF_INSPECTED = "PROGRAMMER_DIFF_INSPECTED"
    PROGRAMMER_TEST_STARTED = "PROGRAMMER_TEST_STARTED"
    PROGRAMMER_TEST_COMPLETED = "PROGRAMMER_TEST_COMPLETED"
    PROGRAMMER_BUILD_STARTED = "PROGRAMMER_BUILD_STARTED"
    PROGRAMMER_BUILD_COMPLETED = "PROGRAMMER_BUILD_COMPLETED"
    PROGRAMMER_SELF_REVIEW_COMPLETED = "PROGRAMMER_SELF_REVIEW_COMPLETED"
    PROGRAMMER_BLOCKED = "PROGRAMMER_BLOCKED"
    PROGRAMMER_COMPLETED = "PROGRAMMER_COMPLETED"
    PROGRAMMER_FAILED = "PROGRAMMER_FAILED"
    PROGRAMMER_CANCELLED = "PROGRAMMER_CANCELLED"

    # Tester Specialist Worker Events (Stage 13)
    TESTER_REQUESTED = "TESTER_REQUESTED"
    TESTER_STARTED = "TESTER_STARTED"
    TEST_PLAN_CREATED = "TEST_PLAN_CREATED"
    TEST_STARTED = "TEST_STARTED"
    TEST_COMPLETED = "TEST_COMPLETED"
    TEST_FAILED = "TEST_FAILED"
    DEFECT_DETECTED = "DEFECT_DETECTED"
    REGRESSION_DETECTED = "REGRESSION_DETECTED"
    UI_TEST_STARTED = "UI_TEST_STARTED"
    UI_TEST_COMPLETED = "UI_TEST_COMPLETED"
    TESTER_COMPLETED = "TESTER_COMPLETED"
    TESTER_FAILED = "TESTER_FAILED"
    TESTER_BLOCKED = "TESTER_BLOCKED"
    TESTER_CANCELLED = "TESTER_CANCELLED"

    # Workforce Workflow & Collaboration Events (Stage 14)
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    WORKFLOW_STATUS_CHANGED = "WORKFLOW_STATUS_CHANGED"
    WORKFLOW_HANDOFF_EXECUTED = "WORKFLOW_HANDOFF_EXECUTED"
    WORKFLOW_STEP_COMPLETED = "WORKFLOW_STEP_COMPLETED"
    WORKFLOW_RETRY_TRIGGERED = "WORKFLOW_RETRY_TRIGGERED"
    WORKFLOW_REASSIGNED = "WORKFLOW_REASSIGNED"
    WORKFLOW_BLOCKED = "WORKFLOW_BLOCKED"
    WORKFLOW_PAUSED = "WORKFLOW_PAUSED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
    WORKFLOW_APPROVAL_REQUESTED = "WORKFLOW_APPROVAL_REQUESTED"
    WORKFLOW_APPROVED = "WORKFLOW_APPROVED"
    WORKFLOW_REJECTED = "WORKFLOW_REJECTED"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    WORKFLOW_STAGNATION_DETECTED = "WORKFLOW_STAGNATION_DETECTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"

    # Human-in-the-Loop & Autonomy Control Events (Stage 15)
    AUTONOMY_POLICY_CREATED = "AUTONOMY_POLICY_CREATED"
    AUTONOMY_POLICY_UPDATED = "AUTONOMY_POLICY_UPDATED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    USER_INPUT_REQUESTED = "USER_INPUT_REQUESTED"
    USER_INPUT_RECEIVED = "USER_INPUT_RECEIVED"
    DECISION_REQUESTED = "DECISION_REQUESTED"
    DECISION_RECEIVED = "DECISION_RECEIVED"
    EMERGENCY_STOP_ACTIVATED = "EMERGENCY_STOP_ACTIVATED"
    EMERGENCY_STOP_CLEARED = "EMERGENCY_STOP_CLEARED"
    ACTION_BLOCKED_BY_POLICY = "ACTION_BLOCKED_BY_POLICY"
    ACTION_ALLOWED_BY_POLICY = "ACTION_ALLOWED_BY_POLICY"

    # System & Failure Events
    RUNTIME_ERROR = "RUNTIME_ERROR"
    EXECUTION_FAILED = "EXECUTION_FAILED"


class EventSource(str, Enum):
    """Originator of the event."""
    SYSTEM = "SYSTEM"
    RUNTIME = "RUNTIME"
    TASK_ENGINE = "TASK_ENGINE"
    WORKER = "WORKER"
    MANAGER = "MANAGER"
    USER = "USER"
