from enum import Enum


class EventType(str, Enum):
    """Authoritative taxonomy of events in the AutonomOS runtime."""

    # Project Events
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_DELETED = "PROJECT_DELETED"

    # Worker Events
    WORKER_REGISTERED = "WORKER_REGISTERED"
    WORKER_UPDATED = "WORKER_UPDATED"
    WORKER_ASSIGNED = "WORKER_ASSIGNED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_REPORTING = "WORKER_REPORTING"
    WORKER_FINISHED = "WORKER_FINISHED"
    WORKER_FAILED = "WORKER_FAILED"
    WORKER_BECAME_IDLE = "WORKER_BECAME_IDLE"
    WORKER_REMOVED = "WORKER_REMOVED"

    # Task Events
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_READY = "TASK_READY"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STARTED = "TASK_STARTED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_RETRYING = "TASK_RETRYING"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"

    # Dependency Events
    DEPENDENCY_ADDED = "DEPENDENCY_ADDED"
    DEPENDENCY_REMOVED = "DEPENDENCY_REMOVED"
    DEPENDENCY_SATISFIED = "DEPENDENCY_SATISFIED"
    DEPENDENCY_CYCLE_DETECTED = "DEPENDENCY_CYCLE_DETECTED"

    # Artifact Events
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    ARTIFACT_UPDATED = "ARTIFACT_UPDATED"
    ARTIFACT_DELETED = "ARTIFACT_DELETED"

    # Evidence & Governance Events
    EVIDENCE_RECORDED = "EVIDENCE_RECORDED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_RESOLVED = "APPROVAL_RESOLVED"

    # Memory & Knowledge Events (Stage 3)
    MEMORY_CREATED = "MEMORY_CREATED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    MEMORY_DELETED = "MEMORY_DELETED"
    DECISION_CREATED = "DECISION_CREATED"
    REPORT_CREATED = "REPORT_CREATED"
    ISSUE_RECORDED = "ISSUE_RECORDED"
    ISSUE_UPDATED = "ISSUE_UPDATED"

    # Worker-Emitted Information (Explicitly non-authoritative worker self-reports)
    WORKER_PROGRESS_LOGGED = "WORKER_PROGRESS_LOGGED"
    WORKER_OUTPUT_PRODUCED = "WORKER_OUTPUT_PRODUCED"

    # System & Failure Events
    RUNTIME_ERROR = "RUNTIME_ERROR"
    EXECUTION_FAILED = "EXECUTION_FAILED"


class EventSource(str, Enum):
    """Originator of the event."""
    SYSTEM = "SYSTEM"
    RUNTIME = "RUNTIME"
    TASK_ENGINE = "TASK_ENGINE"
    WORKER = "WORKER"
    USER = "USER"
